version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_service
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - '8080:8080'
    environment:
      ENV: local
      PORT: ':8080'
      DATABASE_CONN_URL: 'postgres://postgres:postgres@postgres:5432/notification_service?sslmode=disable'
      LOG_ROOT_PATH: /app/logs
      LOG_LEVEL: debug
      SHUTDOWN_TIMEOUT: 15s
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
